### ISSUE TITLE
001 Update package to reflect changes in ModelPath and EnsemblePath renaming and refactoring

### ISSUE THREAD

**Issue by smellycloud** [views-platform/views-stepshifter#2]
## **Title**
Update views_stepshifter package to reflect changes in ModelPath and EnsemblePath renaming and refactoring.

## **Description**
This issue aims to update the views_stepshifter package to reflect the renaming of ModelPath and EnsemblePath classes to ModelPathManager and EnsemblePathManager respectively. Additionally, it involves updating the imports and references to these classes across the codebase to match the new structure. For more information, see [this](https://github.com/views-platform/views-pipeline-core/issues/3).

## **Motivation**
This change is necessary to maintain consistency across the codebase after the renaming and refactoring of ModelPath and EnsemblePath classes. It will improve the clarity and organization of the codebase, making it easier for developers to understand and maintain the code.

## **Proposed Solution**
1. Rename ModelPath to ModelPathManager and EnsemblePath to EnsemblePathManager.
2. Update imports across the `views_stepshifter` package to reflect these changes. For example:
```python
from views_pipeline_core.managers.model import ModelPathManager, ModelManager
from views_pipeline_core.managers.ensemble import EnsemblePathManager, EnsembleManager
```
3. Ensure that all references to ModelPath and EnsemblePath are updated in the codebase, including documentation and comments.
4. Verify that all tests pass after making these changes.

## **Branch**
- Work on a new branch named `feature_001_refactor_managers`

**Comment by lujzi05** [comment]
I like it very much, makes sense
